# Generated by Django 2.2.1 on 2019-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'admin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='imgDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=20)),
                ('patientID', models.CharField(max_length=20)),
                ('houspitalID', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('modality', models.CharField(max_length=10)),
                ('checkMethod', models.CharField(max_length=20)),
                ('checkDate', models.CharField(max_length=20)),
                ('checkDevice', models.CharField(max_length=10)),
                ('imgReport', models.CharField(max_length=500)),
                ('reportResult', models.CharField(max_length=20)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('imgPath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'imgDataInfo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pathoDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=20)),
                ('houspitalID', models.CharField(max_length=15)),
                ('pathoID', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('pathoReport', models.CharField(max_length=1000)),
                ('tumorS', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=30)),
                ('TNM', models.CharField(max_length=10)),
                ('differentiation', models.CharField(max_length=10)),
                ('tumorClass', models.CharField(max_length=20)),
                ('pathoPath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pathoDataInfo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='patientBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=20)),
                ('patientID', models.CharField(max_length=20)),
                ('houspitalID', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('BMI', models.CharField(max_length=5)),
                ('smokingH', models.CharField(max_length=20)),
                ('GeneticH', models.CharField(max_length=20)),
                ('isExisted', models.CharField(max_length=10)),
                ('tumorClass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'patientbasicinfo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tumorMarkerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=20)),
                ('houspitalID', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('CA199', models.CharField(max_length=10)),
                ('CA50', models.CharField(max_length=10)),
                ('CEA', models.CharField(max_length=10)),
                ('CA242', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tumorMarkerInfo',
                'ordering': ['id'],
            },
        ),
    ]
