# Generated by Django 3.0.7 on 2020-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'admin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pancreaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('patientID', models.CharField(max_length=20)),
                ('houspitalID', models.CharField(max_length=20)),
                ('smokingH', models.CharField(max_length=20)),
                ('GeneticH', models.CharField(max_length=20)),
                ('isExisted', models.CharField(max_length=10)),
                ('modality', models.CharField(max_length=10)),
                ('classres', models.CharField(max_length=20)),
                ('segres', models.CharField(max_length=20)),
                ('imgPath', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('BMI', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pancreasedata',
                'ordering': ['id'],
            },
        ),
    ]
